// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package Data;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Data.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string age = 5;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <code>string age = 5;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string password = 6;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 6;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string address = 7;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 7;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string phone = 8;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 8;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string bio = 9;</code>
   * @return The bio.
   */
  java.lang.String getBio();
  /**
   * <code>string bio = 9;</code>
   * @return The bytes for bio.
   */
  com.google.protobuf.ByteString
      getBioBytes();
}
