// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package Data;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\004Data\"\222\001\n\004User\022\n\n\002id\030\001 \001(\t\022" +
      "\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\r\n\005" +
      "email\030\004 \001(\t\022\013\n\003age\030\005 \001(\t\022\020\n\010password\030\006 \001" +
      "(\t\022\017\n\007address\030\007 \001(\t\022\r\n\005phone\030\010 \001(\t\022\013\n\003bi" +
      "o\030\t \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Data_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_User_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Age", "Password", "Address", "Phone", "Bio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
